[package]
name = "rflow"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nn"
path= "src/main.rs"

[dependencies]
indicatif = "0.17.11"
polars = { version = "0.46.0", features = ["csv"] }
rand = "0.9.1"
rand_distr = "0.5.1"
